# Generated by Django 4.0.3 on 2022-06-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images', verbose_name='Photo')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Alt Text')),
            ],
        ),
    ]
